export enum ServerEvents {
  Greeting = 'greeting',
  Hello = 'hello',
  RpsPlay = 'rps:play',
  RpsResult = 'rps:result',
  OddOrEvenPlay = 'odd-or-even:play',
  OddOrEvenResult = 'odd-or-even:result',
  TruthOrDareStart = 'truth-or-dare:start',
  TruthOrDareChoice = 'truth-or-dare:choice',
  TruthOrDareSpin = 'truth-or-dare:spin',
  TruthOrDareContent = 'truth-or-dare:content',
  TruthOrDareAnswer = 'truth-or-dare:answer',
  TruthOrDareAnswerSubmitted = 'truth-or-dare:answer-submitted',
  TruthOrDareValidate = 'truth-or-dare:validate',
  TruthOrDareResult = 'truth-or-dare:result',
  WouldYouRatherStart = 'would-you-rather:start',
  WouldYouRatherChoice = 'would-you-rather:choice',
  WouldYouRatherUpdate = 'would-you-rather:update',
  WouldYouRatherResult = 'would-you-rather:result',
  TwentyQuestionsSetWord = 'twenty-questions:set-word',
  TwentyQuestionsGuess = 'twenty-questions:guess',
  TwentyQuestionsJudge = 'twenty-questions:judge',
  TwentyQuestionsRoundReady = 'twenty-questions:round-ready',
  TwentyQuestionsGuessSubmitted = 'twenty-questions:guess-submitted',
  TwentyQuestionsRoundResult = 'twenty-questions:round-result',
  TwoTruthsOneLieSubmit = 'two-truths-one-lie:submit',
  TwoTruthsOneLieVote = 'two-truths-one-lie:vote',
  TwoTruthsOneLiePrompt = 'two-truths-one-lie:prompt',
  TwoTruthsOneLieResult = 'two-truths-one-lie:result',
  StartGame = 'start-game',
  GameStarted = 'game:started',
  RoomCreated = 'room:created',
  RoomUpdate = 'room:update',
  RoomError = 'room:error',
  ScoreReset = 'score:reset'
}

export enum ClientEvents {
  Connect = 'connection',
  Disconnect = 'disconnect',
  CreateRoom = 'create-room',
  JoinRoom = 'join-room',
  LeaveRoom = 'leave-room',
  ResetMatchScore = 'reset-match-score',
  TwentyQuestionsRequestState = 'twenty-questions:request-state'
}
