export type TruthOrDareCategoryId =
  | 'general'
  | 'amis'
  | 'couple'
  | 'famille'
  | 'audacieux'
  | 'nostalgie'
  | 'vie'
  | 'desir'
  | 'intimite';

export type TruthOrDareCategory = { id: TruthOrDareCategoryId; label: string; description: string };

// Categories a room/player can opt into.
export const TRUTH_OR_DARE_CATEGORIES: TruthOrDareCategory[] = [
  { id: 'general', label: 'Général', description: 'Questions et gages fun, pour tout le monde.' },
  { id: 'amis', label: 'Entre amis', description: 'Souvenirs, anecdotes et complicité de groupe.' },
  { id: 'couple', label: 'Couple / Flirt', description: 'Romantique et tendre, sans être explicite.' },
  { id: 'famille', label: 'Famille', description: 'Souvenirs et traditions familiales, tout public.' },
  { id: 'audacieux', label: 'Audacieux', description: 'Plus embarrassant, mais toujours bon enfant.' },
  { id: 'nostalgie', label: 'Nostalgie', description: 'Enfance et souvenirs d’avant.' },
  { id: 'vie', label: 'Vie & Ambitions', description: 'Objectifs, regrets et rêves pour l’avenir.' },
  { id: 'desir', label: 'Désir & Fantasmes', description: 'Attirance et fantasmes, en toute pudeur — à activer par les deux joueurs.' },
  { id: 'intimite', label: 'Confidences intimes', description: 'Vulnérabilité et intimité de couple — à activer par les deux joueurs.' }
];

// All categories are checked by default — the two-player validation step in the waiting room
// (see roomManager.setTruthOrDareCategories / validateTruthOrDareCategories) is the actual
// safety net: nothing starts until both players explicitly confirm the active set, so either
// player can freely uncheck désir/intimité before validating if they'd rather not include them.
export const DEFAULT_TRUTH_OR_DARE_CATEGORY_IDS: TruthOrDareCategoryId[] = TRUTH_OR_DARE_CATEGORIES.map(category => category.id);

export type TruthOrDarePrompt = { truth: string; dare: string; category: TruthOrDareCategoryId };
export type WouldYouRatherPrompt = { left: string; right: string };

export const truthOrDarePrompts: TruthOrDarePrompt[] = [
  // --- Général / Fun ---
  { truth: 'Quelle est ta plus grande peur ?', dare: 'Chante le refrain de ta chanson préférée.', category: 'general' },
  { truth: 'Quel est ton plus grand secret ?', dare: 'Fais 10 sauts en étoile.', category: 'general' },
  { truth: 'Quel est ton rêve le plus étrange ?', dare: 'Imite un animal pendant 15 secondes.', category: 'general' },
  { truth: 'Quelle est la chose la plus embarrassante que tu aies faite ?', dare: 'Parle avec un accent au choix pendant 1 minute.', category: 'general' },
  { truth: 'Quel est ton plus grand regret ?', dare: 'Fais une danse improvisée pendant 20 secondes.', category: 'general' },
  { truth: 'As-tu déjà menti à un proche pour éviter un conflit ?', dare: 'Raconte une blague, même mauvaise.', category: 'general' },
  { truth: 'Quelle est la chose la plus folle que tu aimerais essayer un jour ?', dare: 'Fais 15 pompes, ou l’équivalent avec les genoux au sol.', category: 'general' },
  { truth: 'Quel est ton talent caché ?', dare: 'Imite la voix d’un personnage célèbre.', category: 'general' },
  { truth: 'Quelle est la pire excuse que tu aies inventée ?', dare: 'Fais 30 secondes de mime pour décrire ton métier.', category: 'general' },
  { truth: 'Quel est l’objet le plus inutile que tu aies acheté ?', dare: 'Récite l’alphabet à l’envers.', category: 'general' },
  { truth: 'Quelle appli passes-tu le plus de temps à utiliser ?', dare: 'Imite la façon de marcher d’un mannequin.', category: 'general' },
  { truth: 'Quelle est la chanson dont tu as le plus honte de connaître les paroles par cœur ?', dare: 'Chante cette chanson maintenant.', category: 'general' },
  { truth: 'Quel est ton pire trait de caractère ?', dare: 'Fais rire quelqu’un du groupe sans dire un mot.', category: 'general' },
  { truth: 'Quelle est la dernière chose stupide que tu as googlée ?', dare: 'Décris ton plat préféré comme si tu vendais des voitures.', category: 'general' },
  { truth: 'Quel est ton plus grand fail en public ?', dare: 'Marche comme un robot pendant 20 secondes.', category: 'general' },
  { truth: 'Quelle habitude bizarre as-tu que peu de gens connaissent ?', dare: 'Fais ton meilleur rire de sorcière.', category: 'general' },
  { truth: 'Quel mensonge racontes-tu le plus souvent ?', dare: 'Improvise un mini discours de remerciement aux Oscars.', category: 'general' },
  { truth: 'Quelle est la chose la plus gênante trouvée dans ton historique de recherche ?', dare: 'Fais 10 squats en comptant à voix haute.', category: 'general' },
  { truth: 'Quel est ton plus grand complexe ?', dare: 'Invente un super-héros et présente-le en 30 secondes.', category: 'general' },
  { truth: 'Quelle est la pire coiffure que tu aies eue ?', dare: 'Coiffe-toi n’importe comment pendant 2 minutes.', category: 'general' },
  { truth: 'Quel est le compliment qui t’a le plus touché ?', dare: 'Fais un compliment sincère à chaque joueur.', category: 'general' },
  { truth: 'Quelle est ta plus grande superstition ?', dare: 'Raconte une histoire de fantômes improvisée.', category: 'general' },
  { truth: 'Quel est le film que tu prétends avoir vu sans jamais l’avoir vu ?', dare: 'Résume ce film comme si tu l’avais vraiment vu.', category: 'general' },
  { truth: 'Quel est ton plus grand vice ?', dare: 'Fais ta meilleure imitation d’un présentateur télé.', category: 'general' },
  { truth: 'Quelle est la chose la plus chère que tu aies perdue ou cassée ?', dare: 'Fais 15 secondes de moonwalk (ou ta meilleure tentative).', category: 'general' },

  // --- Entre amis ---
  { truth: 'Qui, dans ce groupe, ferait le meilleur partenaire de crime ?', dare: 'Fais un compliment à la personne à ta gauche sans sourire.', category: 'amis' },
  { truth: 'Quel est le surnom le plus gênant qu’on t’ait donné ?', dare: 'Laisse quelqu’un du groupe poster un statut à ta place (surveillé).', category: 'amis' },
  { truth: 'Quelle est la dispute la plus stupide que tu aies eue avec un ami ?', dare: 'Imite la façon de parler d’un ami présent (gentiment).', category: 'amis' },
  { truth: 'As-tu déjà été jaloux d’un ami ? Pourquoi ?', dare: 'Fais une accolade à chaque personne du groupe.', category: 'amis' },
  { truth: 'Quel ami connais-tu depuis le plus longtemps et pourquoi êtes-vous restés proches ?', dare: 'Raconte le pire souvenir de soirée que tu as vécu avec ce groupe.', category: 'amis' },
  { truth: 'Quelle est la chose la plus folle que tu aies faite pour impressionner un ami ?', dare: 'Fais un défi de grimace avec la personne en face de toi, le premier qui rit a perdu.', category: 'amis' },
  { truth: 'As-tu déjà emprunté quelque chose à un ami sans lui rendre ?', dare: 'Envoie un message vocal ridicule à un contact au hasard (approuvé par le groupe).', category: 'amis' },
  { truth: 'Qui dans ce groupe te fait le plus rire et pourquoi ?', dare: 'Imite la personne à ta droite pendant 20 secondes.', category: 'amis' },
  { truth: 'Quel est le pire cadeau qu’un ami t’ait offert ?', dare: 'Fais un discours improvisé sur pourquoi ce groupe est le meilleur.', category: 'amis' },
  { truth: 'As-tu déjà eu le béguin pour l’ami(e) d’un ami ?', dare: 'Raconte ta pire soirée ratée en 30 secondes chrono.', category: 'amis' },
  { truth: 'Quelle rumeur as-tu déjà fait circuler sans être sûr qu’elle soit vraie ?', dare: 'Fais deviner un film aux autres uniquement en mimant.', category: 'amis' },
  { truth: 'Quel est le service le plus embarrassant que tu aies demandé à un ami ?', dare: 'Chante « joyeux anniversaire » à quelqu’un du groupe, même si ce n’est pas son anniversaire.', category: 'amis' },
  { truth: 'As-tu déjà annulé un plan pour une raison bidon ?', dare: 'Imite comment tu te comportes quand tu es fatigué·e.', category: 'amis' },
  { truth: 'Quel est le surnom que tu donnerais à chaque personne ici si tu devais en choisir un ?', dare: 'Fais un high-five à chaque joueur en inventant un mot de passe secret à chaque fois.', category: 'amis' },
  { truth: 'Quelle est la chose la plus gênante que tu aies faite devant ce groupe ?', dare: 'Raconte une blague en essayant de ne pas rire toi-même.', category: 'amis' },
  { truth: 'As-tu déjà menti pour éviter une soirée ?', dare: 'Fais deviner ton animal préféré uniquement avec des sons.', category: 'amis' },
  { truth: 'Quel ami te connaît le mieux selon toi ?', dare: 'Laisse le groupe choisir ta prochaine phrase et dis-la avec le plus de conviction possible.', category: 'amis' },
  { truth: 'Quelle est ta pire habitude quand tu es en groupe ?', dare: 'Fais une impression de chaque personne présente en une phrase.', category: 'amis' },
  { truth: 'As-tu déjà eu peur de perdre un ami à cause d’un malentendu ?', dare: 'Improvise une chanson sur la personne à ta gauche.', category: 'amis' },
  { truth: 'Quel est le plan le plus fou que tu as accepté juste pour ne pas décevoir tes amis ?', dare: 'Fais 20 secondes de « statue » sans bouger, peu importe ce que les autres font pour te déconcentrer.', category: 'amis' },

  // --- Couple / Flirt ---
  { truth: 'Quel a été ton premier vrai coup de cœur ?', dare: 'Fais un compliment romantique à ton/ta partenaire (ou à la personne de ton choix).', category: 'couple' },
  { truth: 'Quelle qualité te fait immédiatement craquer chez quelqu’un ?', dare: 'Fais un regard de séducteur/séductrice pendant 10 secondes sans rire.', category: 'couple' },
  { truth: 'Quel est ton souvenir de rendez-vous romantique préféré ?', dare: 'Décris ton/ta partenaire idéal·e en 3 mots, à voix haute.', category: 'couple' },
  { truth: 'As-tu déjà eu le cœur brisé ? Raconte, sans donner de nom.', dare: 'Écris un petit mot doux et donne-le à quelqu’un du groupe.', category: 'couple' },
  { truth: 'Quel est le geste romantique que tu adores recevoir ?', dare: 'Fais un slow imaginaire de 10 secondes avec une chaise.', category: 'couple' },
  { truth: 'Quelle est la chose la plus romantique que tu aies faite pour quelqu’un ?', dare: 'Chante une chanson d’amour, même mal.', category: 'couple' },
  { truth: 'Préfères-tu recevoir des mots doux ou des gestes pour te sentir aimé·e ?', dare: 'Décris ton premier baiser sans donner de détails trop précis.', category: 'couple' },
  { truth: 'Quel est ton plus grand fantasme romantique (version soft) ?', dare: 'Fais un compliment sincère à trois personnes du groupe.', category: 'couple' },
  { truth: 'As-tu déjà envoyé un message que tu regrettes à quelqu’un que tu aimais ?', dare: 'Invente une demande en mariage improvisée et fais-la à quelqu’un.', category: 'couple' },
  { truth: 'Quelle chanson te fait immédiatement penser à quelqu’un que tu as aimé ?', dare: 'Fais un câlin de 10 secondes à la personne de ton choix.', category: 'couple' },
  { truth: 'Crois-tu au coup de foudre ?', dare: 'Récite un poème d’amour improvisé de 4 lignes.', category: 'couple' },
  { truth: 'Quel est le rendez-vous idéal pour toi ?', dare: 'Fais semblant de draguer quelqu’un du groupe avec les pires phrases d’accroche possibles.', category: 'couple' },
  { truth: 'Qu’est-ce qui te fait le plus rougir chez une personne que tu aimes ?', dare: 'Fixe la personne en face de toi dans les yeux pendant 20 secondes sans rire.', category: 'couple' },
  { truth: 'Quel est ton langage de l’amour (mots, cadeaux, gestes, temps, contact) ?', dare: 'Décris ton/ta partenaire (ou crush) sans jamais dire son prénom.', category: 'couple' },
  { truth: 'As-tu déjà été amoureux/amoureuse de deux personnes en même temps ?', dare: 'Fais une déclaration d’amour à un objet dans la pièce, avec le plus de sérieux possible.', category: 'couple' },
  { truth: 'Quelle est la qualité que tu apprécies le plus chez ton/ta partenaire ?', dare: 'Raconte votre rencontre comme si c’était un film à gros budget.', category: 'couple' },
  { truth: 'Quel est ton pire moment de gêne pendant un date ?', dare: 'Envoie un message doux à ton/ta partenaire maintenant (ou écris-en un que tu garderas pour plus tard).', category: 'couple' },
  { truth: 'Quelle est la chose la plus mignonne que ton/ta partenaire fait sans le savoir ?', dare: 'Imite la façon dont vous vous êtes rencontrés, en exagérant tout.', category: 'couple' },
  { truth: 'As-tu déjà été jaloux/jalouse sans raison valable ?', dare: 'Fais un compliment original (pas sur le physique) à ton/ta partenaire.', category: 'couple' },
  { truth: 'Quel est ton souvenir préféré avec ton/ta partenaire ?', dare: 'Danse un slow de 15 secondes avec ton/ta partenaire (ou seul·e).', category: 'couple' },
  { truth: 'Quelle habitude de ton/ta partenaire te fait fondre ?', dare: 'Raconte à voix haute ce que tu préfères chez la personne à ta droite.', category: 'couple' },
  { truth: 'Quel serait ton rendez-vous de rêve, sans limite de budget ?', dare: 'Fais un massage d’épaules de 20 secondes à ton/ta partenaire.', category: 'couple' },
  { truth: 'Quelle est la chose la plus douce qu’on t’ait jamais dite ?', dare: 'Invente un surnom affectueux pour ton/ta partenaire et utilise-le pour le reste de la partie.', category: 'couple' },
  { truth: 'As-tu un rituel ou une petite habitude romantique avec ton/ta partenaire ?', dare: 'Fais une liste de 3 choses que tu adores chez ton/ta partenaire, à voix haute.', category: 'couple' },
  { truth: 'Quelle est la première chose que tu as remarquée chez ton/ta partenaire ?', dare: 'Offre un compliment inattendu à quelqu’un que tu ne connais pas très bien dans le groupe.', category: 'couple' },

  // --- Famille ---
  { truth: 'Quel est ton souvenir d’enfance préféré en famille ?', dare: 'Imite un membre de ta famille (avec bienveillance).', category: 'famille' },
  { truth: 'Quelle tradition familiale préfères-tu ?', dare: 'Raconte ta blague de famille préférée.', category: 'famille' },
  { truth: 'Quel plat de famille te manque le plus quand tu es loin de chez toi ?', dare: 'Décris la recette de ce plat comme un grand chef.', category: 'famille' },
  { truth: 'Qui, dans ta famille, te ressemble le plus en caractère ?', dare: 'Imite la voix d’un parent ou grand-parent (gentiment).', category: 'famille' },
  { truth: 'Quel est le conseil de famille qui t’a le plus marqué ?', dare: 'Fais une annonce familiale improvisée et solennelle.', category: 'famille' },
  { truth: 'Quelle bêtise as-tu faite enfant que tes parents ignorent peut-être encore ?', dare: 'Chante une comptine de ton enfance.', category: 'famille' },
  { truth: 'Quel est ton meilleur souvenir de vacances en famille ?', dare: 'Raconte une anecdote de famille comme si c’était un film d’action.', category: 'famille' },
  { truth: 'Quelle leçon de vie ta famille t’a-t-elle apprise ?', dare: 'Fais une imitation d’un repas de famille animé.', category: 'famille' },
  { truth: 'Quel surnom te donnait-on enfant dans ta famille ?', dare: 'Raconte ton pire caprice d’enfant.', category: 'famille' },
  { truth: 'Quelle est la règle familiale que tu trouvais la plus injuste enfant ?', dare: 'Fais un discours de remerciement à ta famille comme si tu recevais un prix.', category: 'famille' },
  { truth: 'Quel membre de ta famille t’a le plus inspiré ?', dare: 'Décris ta famille en 5 mots, à voix haute.', category: 'famille' },
  { truth: 'Quelle est la chose la plus drôle qu’un enfant de ta famille ait dite ?', dare: 'Raconte comment tu occupais tes journées d’été étant enfant.', category: 'famille' },
  { truth: 'Quel jeu de société ou jeu de cartes joues-tu (ou jouais-tu) le plus en famille ?', dare: 'Mime ton jeu de société préféré sans parler.', category: 'famille' },
  { truth: 'Quelle est ta meilleure blague de famille (celle qui revient à chaque repas) ?', dare: 'Imite comment ta famille réagit à une bonne nouvelle.', category: 'famille' },
  { truth: 'Quel est le plus beau compliment qu’un parent t’ait fait ?', dare: 'Fais une déclaration d’amour à ta famille, façon discours officiel.', category: 'famille' },
  { truth: 'Quelle fête de famille préfères-tu et pourquoi ?', dare: 'Raconte le pire cadeau que tu aies reçu d’un proche (avec le sourire).', category: 'famille' },
  { truth: 'Quel est ton meilleur souvenir avec tes grands-parents ?', dare: 'Imite la façon dont un grand-parent raconte une histoire.', category: 'famille' },
  { truth: 'Quelle valeur familiale essaies-tu de transmettre autour de toi ?', dare: 'Raconte une histoire drôle que tes parents racontent souvent sur toi.', category: 'famille' },
  { truth: 'Quel est le voyage en famille dont tu te souviens le mieux ?', dare: 'Décris ta famille comme si tu la présentais dans une émission de télé-réalité.', category: 'famille' },
  { truth: 'Quelle habitude de tes parents as-tu fini par adopter toi-même ?', dare: 'Fais une pose de photo de famille improvisée avec le groupe.', category: 'famille' },

  // --- Audacieux / Embarrassant (mais soft) ---
  { truth: 'Quelle est la chose la plus étrange que tu aies mangée ?', dare: 'Laisse quelqu’un du groupe te dessiner une moustache (au feutre lavable).', category: 'audacieux' },
  { truth: 'Quel est ton pire souvenir d’audition, d’examen ou d’entretien raté ?', dare: 'Marche comme un canard pendant 15 secondes.', category: 'audacieux' },
  { truth: 'As-tu déjà été surpris·e en train de parler tout seul·e ?', dare: 'Fais ta pire imitation de star de cinéma.', category: 'audacieux' },
  { truth: 'Quelle est la note la plus basse que tu aies eue à l’école ?', dare: 'Chante une chanson en changeant les paroles pour parler du groupe.', category: 'audacieux' },
  { truth: 'As-tu déjà eu un accident gênant en public (trébucher, renverser un verre…) ?', dare: 'Refais la scène de cet accident en mode théâtral.', category: 'audacieux' },
  { truth: 'Quel est le vêtement le plus ridicule que tu aies porté ?', dare: 'Porte un vêtement à l’envers pour le reste de la manche.', category: 'audacieux' },
  { truth: 'As-tu déjà envoyé un message au mauvais destinataire ?', dare: 'Laisse le groupe choisir ton statut de réseau social pour les 10 prochaines minutes.', category: 'audacieux' },
  { truth: 'Quelle est ta pire technique de drague ratée ?', dare: 'Fais ta meilleure démonstration de drague ratée devant le groupe.', category: 'audacieux' },
  { truth: 'As-tu déjà fait semblant d’être malade pour éviter quelque chose ?', dare: 'Fais semblant d’être malade de la manière la plus théâtrale possible.', category: 'audacieux' },
  { truth: 'Quelle est la chose la plus ridicule que tu aies faite pour de l’argent ?', dare: 'Propose de laver la vaisselle (ou une tâche) du prochain gagnant de la partie.', category: 'audacieux' },
  { truth: 'As-tu déjà chanté ou dansé en pensant que personne ne te regardait, avant d’être vu·e ?', dare: 'Refais cette danse maintenant.', category: 'audacieux' },
  { truth: 'Quel est le mensonge le plus absurde que tu aies raconté pour te sortir d’une situation ?', dare: 'Invente un mensonge absurde maintenant et fais semblant d’y croire.', category: 'audacieux' },
  { truth: 'As-tu déjà eu un fou rire au pire moment possible ?', dare: 'Essaie de garder ton sérieux pendant que le groupe essaie de te faire rire (30 secondes).', category: 'audacieux' },
  { truth: 'Quelle est ta pire coupe de cheveux de l’adolescence ?', dare: 'Décris cette coupe de cheveux comme un styliste la présenterait sur un podium.', category: 'audacieux' },
  { truth: 'As-tu déjà été à côté de la plaque en pensant qu’on flirtait avec toi ?', dare: 'Fais ta meilleure scène de flirt exagérée avec un objet de la pièce.', category: 'audacieux' },

  // --- Nostalgie / Enfance ---
  { truth: 'Quel dessin animé regardais-tu en boucle enfant ?', dare: 'Chante le générique d’un dessin animé de ton enfance.', category: 'nostalgie' },
  { truth: 'Quel était ton jouet préféré étant enfant ?', dare: 'Mime ton jouet préféré sans le nommer.', category: 'nostalgie' },
  { truth: 'Quel métier voulais-tu faire quand tu étais petit·e ?', dare: 'Fais une présentation de ce métier de rêve comme à la maternelle.', category: 'nostalgie' },
  { truth: 'Quelle était ta plus grande peur d’enfant ?', dare: 'Raconte l’histoire qui te faisait le plus peur enfant.', category: 'nostalgie' },
  { truth: 'Quel est ton meilleur souvenir de récré ?', dare: 'Fais ton jeu de cour de récré préféré, mimé.', category: 'nostalgie' },
  { truth: 'Quelle chanson d’enfance connais-tu encore par cœur ?', dare: 'Chante cette chanson maintenant.', category: 'nostalgie' },
  { truth: 'As-tu eu un ami imaginaire ? Décris-le.', dare: 'Présente ton ami imaginaire (ou invente-en un) au groupe.', category: 'nostalgie' },
  { truth: 'Quel était ton surnom d’école ?', dare: 'Fais l’imitation d’un prof marquant de ta scolarité.', category: 'nostalgie' },
  { truth: 'Quelle bêtise as-tu faite à l’école dont tu es encore fier/fière ?', dare: 'Raconte cette bêtise comme si c’était une légende.', category: 'nostalgie' },
  { truth: 'Quel est le premier concert ou spectacle que tu aies vu ?', dare: 'Chante un extrait d’une chanson de cette époque.', category: 'nostalgie' },

  // --- Vie / Ambitions ---
  { truth: 'Quel est ton plus grand objectif de vie pour les 5 prochaines années ?', dare: 'Fais un discours de motivation à quelqu’un du groupe.', category: 'vie' },
  { truth: 'Si tu pouvais changer un choix de ton passé, lequel serait-ce ?', dare: 'Décris ta vie idéale dans 10 ans en 30 secondes.', category: 'vie' },
  { truth: 'Quelle est la peur qui t’empêche le plus d’avancer dans la vie ?', dare: 'Fais une liste de 3 choses dont tu es fier/fière.', category: 'vie' },
  { truth: 'Quel conseil donnerais-tu à la version de toi d’il y a 10 ans ?', dare: 'Écris une carte postale imaginaire à ton futur toi.', category: 'vie' },
  { truth: 'Quel est le rêve que tu n’as jamais osé poursuivre ?', dare: 'Présente ce rêve comme si tu cherchais des investisseurs.', category: 'vie' },
  { truth: 'Qu’est-ce qui te rend le plus fier/fière dans ta vie actuelle ?', dare: 'Fais un « discours de victoire » comme si tu venais de gagner un prix.', category: 'vie' },
  { truth: 'Quelle habitude aimerais-tu changer chez toi ?', dare: 'Fais 20 secondes de méditation guidée improvisée pour le groupe.', category: 'vie' },
  { truth: 'Quel est le meilleur conseil qu’on t’ait donné dans la vie ?', dare: 'Donne un conseil de vie sérieux (ou complètement absurde) à chaque joueur.', category: 'vie' },
  { truth: 'Quelle décision a le plus changé le cours de ta vie ?', dare: 'Raconte ta journée idéale du début à la fin, en 30 secondes.', category: 'vie' },
  { truth: 'Si l’argent n’était pas un problème, que ferais-tu de tes journées ?', dare: 'Présente ton futur job de rêve comme dans une pub télé.', category: 'vie' },
  { truth: 'Quelle est la chose que tu voudrais accomplir avant tes 30/40/50 ans ?', dare: 'Fais une bucket-list de 3 choses à voix haute.', category: 'vie' },
  { truth: 'Qu’est-ce qui te fait le plus peur concernant l’avenir ?', dare: 'Décris comment tu imagines le monde dans 50 ans.', category: 'vie' },
  { truth: 'Quel est ton plus grand accomplissement à ce jour ?', dare: 'Fais applaudir le groupe pour ton plus grand accomplissement, façon cérémonie.', category: 'vie' },
  { truth: 'Quelle carrière aurais-tu choisie dans une autre vie ?', dare: 'Présente-toi comme si tu passais un entretien pour ce métier.', category: 'vie' },
  { truth: 'Quel est le plus grand risque que tu aies pris dans ta vie ?', dare: 'Raconte ce risque comme la bande-annonce d’un film.', category: 'vie' },

  // --- Désir & Fantasmes ---
  { truth: 'Qu’est-ce qui déclenche le plus le désir chez toi : un mot, un geste, un regard ?', dare: 'Décris en une phrase ce qui te rend irrésistible selon toi.', category: 'desir' },
  { truth: 'Quel est le fantasme romantique que tu n’as jamais osé partager ?', dare: 'Chuchote une phrase séduisante à l’oreille de ton/ta partenaire.', category: 'desir' },
  { truth: 'Quel vêtement ou style trouves-tu le plus séduisant chez ton/ta partenaire ?', dare: 'Fais un regard intense à ton/ta partenaire pendant 15 secondes, sans parler.', category: 'desir' },
  { truth: 'Quel est le moment où tu as ressenti le plus de désir pour ton/ta partenaire, sans entrer dans les détails ?', dare: 'Décris, à voix basse, ce que tu aimerais qu’il/elle te fasse ce soir (en restant pudique).', category: 'desir' },
  { truth: 'Préfères-tu la séduction lente ou l’attirance immédiate et intense ?', dare: 'Fais un compliment sur le corps de ton/ta partenaire, avec élégance.', category: 'desir' },
  { truth: 'Quel scénario romantique aimerais-tu vivre au moins une fois ?', dare: 'Retire un vêtement léger (écharpe, veste, chaussettes...) de façon aussi séduisante que possible.', category: 'desir' },
  { truth: 'Qu’est-ce qui te fait te sentir le plus désiré·e par ton/ta partenaire ?', dare: 'Embrasse ton/ta partenaire là où il/elle te désigne (cou, main, front...).', category: 'desir' },
  { truth: 'As-tu un endroit insolite où tu rêverais de vivre un moment intime ?', dare: 'Fais une danse lente et sensuelle de 20 secondes pour ton/ta partenaire.', category: 'desir' },
  { truth: 'Quelle partie du corps de ton/ta partenaire préfères-tu, et pourquoi ?', dare: 'Décris ta tenue de séduction idéale, sur toi ou sur ton/ta partenaire.', category: 'desir' },
  { truth: 'Quel est le compliment le plus sensuel qu’on t’ait fait ?', dare: 'Fais un massage des mains à ton/ta partenaire pendant 30 secondes, en silence.', category: 'desir' },
  { truth: 'Y a-t-il une tenue ou un déguisement qui t’excite particulièrement chez l’autre ?', dare: 'Invente un surnom coquin pour ton/ta partenaire et utilise-le pour le reste de la partie.', category: 'desir' },
  { truth: 'Quel est ton souvenir le plus torride, sans entrer dans les détails explicites ?', dare: 'Décris la première chose que tu ferais si vous étiez seuls là, maintenant.', category: 'desir' },
  { truth: 'Qu’est-ce qui, chez quelqu’un, t’attire instantanément ?', dare: 'Fais semblant de retirer lentement un vêtement imaginaire, façon effeuillage burlesque.', category: 'desir' },
  { truth: 'As-tu déjà eu un fantasme concernant un lieu précis (voyage, endroit insolite) ?', dare: 'Mordille légèrement ta lèvre en regardant ton/ta partenaire pendant 5 secondes.', category: 'desir' },
  { truth: 'Quel est le jeu de séduction que tu préfères (regards, mots, contact) ?', dare: 'Décris la dernière fois où tu as eu vraiment envie de ton/ta partenaire.', category: 'desir' },
  { truth: 'Que penses-tu de l’idée de réaliser un fantasme ensemble un jour ?', dare: 'Fais une promesse coquine à ton/ta partenaire pour plus tard dans la soirée.', category: 'desir' },
  { truth: 'Quel est le moment de la journée où tu te sens le/la plus désirable ?', dare: 'Trace du doigt une ligne imaginaire le long du bras de ton/ta partenaire.', category: 'desir' },
  { truth: 'Quelle chanson te met immédiatement dans une ambiance sensuelle ?', dare: 'Fais durer un regard complice avec ton/ta partenaire pendant 10 secondes, sans rire.', category: 'desir' },
  { truth: 'As-tu un rituel avant un moment intime (musique, lumière, ambiance) ?', dare: 'Souffle doucement dans le cou de ton/ta partenaire.', category: 'desir' },
  { truth: 'Qu’aimerais-tu que ton/ta partenaire ose plus souvent avec toi ?', dare: 'Décris, geste à l’appui, ta façon idéale d’être embrassé·e.', category: 'desir' },

  // --- Confidences intimes ---
  { truth: 'Qu’est-ce qui te fait te sentir le plus en sécurité émotionnellement avec ton/ta partenaire ?', dare: 'Dis à voix haute une chose que tu n’as jamais osé avouer à ton/ta partenaire (rien de grave, juste inavoué).', category: 'intimite' },
  { truth: 'Quelle est ta plus grande peur dans une relation de couple ?', dare: 'Décris ce que « l’amour » signifie pour toi, en une phrase sincère.', category: 'intimite' },
  { truth: 'As-tu déjà eu du mal à dire « je t’aime » en premier ? Pourquoi ?', dare: 'Regarde ton/ta partenaire et termine la phrase « Ce que j’admire le plus chez toi, c’est... ».', category: 'intimite' },
  { truth: 'Quelle est la chose que tu attends le plus de ton/ta partenaire émotionnellement ?', dare: 'Raconte un moment où tu t’es senti·e vraiment vu·e et compris·e par ton/ta partenaire.', category: 'intimite' },
  { truth: 'Qu’est-ce qui t’aide à te sentir en confiance pour être pleinement toi-même avec quelqu’un ?', dare: 'Partage une insécurité que tu portes depuis longtemps, sans minimiser.', category: 'intimite' },
  { truth: 'As-tu déjà eu peur d’être « trop » ou « pas assez » pour quelqu’un que tu aimais ?', dare: 'Dis à ton/ta partenaire une qualité qu’il/elle ne connaît peut-être pas que tu apprécies chez elle/lui.', category: 'intimite' },
  { truth: 'Quelle est ta définition de l’intimité, au-delà du physique ?', dare: 'Partage un souvenir qui t’a rendu·e vulnérable, et comment tu l’as vécu.', category: 'intimite' },
  { truth: 'Qu’est-ce qui te fait te sentir vraiment écouté·e dans une relation ?', dare: 'Dis une chose que tu voudrais que ton/ta partenaire sache mais que tu n’as jamais formulée.', category: 'intimite' },
  { truth: 'As-tu une blessure du passé qui influence encore la façon dont tu aimes aujourd’hui ?', dare: 'Décris ce dont tu as le plus besoin quand tu te sens vulnérable.', category: 'intimite' },
  { truth: 'Quelle limite personnelle (physique ou émotionnelle) est la plus importante pour toi dans une relation ?', dare: 'Nomme une chose que tu voudrais améliorer dans ta façon de communiquer en couple.', category: 'intimite' },
  { truth: 'Qu’est-ce qui te fait sentir profondément connecté·e à quelqu’un ?', dare: 'Partage ce que la confiance signifie concrètement pour toi.', category: 'intimite' },
  { truth: 'As-tu déjà eu du mal à demander ce dont tu avais besoin dans une relation ?', dare: 'Dis une peur que tu as concernant l’avenir de ta relation actuelle (ou une relation future).', category: 'intimite' },
  { truth: 'Quel est le geste ou mot qui te fait te sentir le plus aimé·e au quotidien ?', dare: 'Partage un souvenir d’enfance qui explique comment tu vis l’attachement aujourd’hui.', category: 'intimite' },
  { truth: 'Qu’est-ce qui pourrait te rendre plus vulnérable avec ton/ta partenaire si tu osais ?', dare: 'Dis une chose que tu pardonnes difficilement, et pourquoi.', category: 'intimite' },
  { truth: 'As-tu peur de l’engagement ? Pourquoi, selon toi ?', dare: 'Termine la phrase « J’ai besoin de toi quand... » à voix haute.', category: 'intimite' },
  { truth: 'Quelle qualité émotionnelle recherches-tu le plus chez un partenaire ?', dare: 'Partage un moment où tu t’es senti·e rejeté·e, et comment tu l’as surmonté.', category: 'intimite' },
  { truth: 'Comment sais-tu que tu peux vraiment faire confiance à quelqu’un ?', dare: 'Dis une chose que tu n’as jamais dite à voix haute sur ce que tu ressens en ce moment.', category: 'intimite' },
  { truth: 'Qu’est-ce qui te fait te sentir le/la plus authentique dans une relation ?', dare: 'Partage ce que tu espères que ton/ta partenaire ne changera jamais chez toi.', category: 'intimite' },
  { truth: 'As-tu déjà eu peur de perdre quelqu’un que tu aimais profondément ?', dare: 'Dis à voix haute ce pour quoi tu es le/la plus reconnaissant·e dans ta relation actuelle.', category: 'intimite' },
  { truth: 'Quelle est la chose la plus importante que tu aies apprise sur toi-même grâce à une relation passée ?', dare: 'Termine la phrase « Avec toi, je me sens... » avec sincérité.', category: 'intimite' }
];

export const wouldYouRatherPrompts: WouldYouRatherPrompt[] = [
  // --- Général / Fun ---
  { left: 'Vivre sans musique', right: 'Vivre sans films' },
  { left: 'Pouvoir voler', right: 'Être invisible' },
  { left: 'Avoir un jet privé', right: 'Avoir une île privée' },
  { left: 'Lire dans les pensées', right: 'Voir le futur' },
  { left: 'Ne plus jamais manger de sucré', right: 'Ne plus jamais manger de salé' },
  { left: 'Vivre à la montagne', right: 'Vivre à la mer' },
  { left: 'Avoir plus de temps libre', right: 'Avoir plus d’argent' },
  { left: 'Parler toutes les langues du monde', right: 'Jouer de tous les instruments de musique' },
  { left: 'Être toujours en retard', right: 'Être toujours trop en avance' },
  { left: 'Avoir une mémoire parfaite', right: 'Avoir une créativité sans limite' },
  { left: 'Perdre tous tes souvenirs d’avant tes 18 ans', right: 'Ne plus pouvoir créer de nouveaux souvenirs' },
  { left: 'Ne plus jamais utiliser de téléphone', right: 'Ne plus jamais regarder de série ou film' },
  { left: 'Vivre sans internet', right: 'Vivre sans voiture' },
  { left: 'Toujours dire la vérité, même blessante', right: 'Pouvoir mentir sans jamais être découvert' },
  { left: 'Être une célébrité adorée mais sans vie privée', right: 'Être anonyme mais libre' },
  { left: 'Revivre le même jour en boucle', right: 'Sauter 10 ans dans le futur d’un coup' },
  { left: 'Ne plus jamais dormir', right: 'Dormir 16 heures par jour' },
  { left: 'Toujours avoir raison', right: 'Toujours avoir de la chance' },
  { left: 'Perdre le sens du goût', right: 'Perdre le sens de l’odorat' },
  { left: 'Vivre 1000 ans mais seul·e', right: 'Vivre 80 ans entouré·e de gens que tu aimes' },
  { left: 'Être capable de parler aux animaux', right: 'Être capable de parler toutes les langues humaines' },
  { left: 'Avoir un rembobinage de 10 secondes dans la vie', right: 'Avoir une pause de 10 secondes dans la vie' },
  { left: 'Savoir exactement quand tu vas mourir', right: 'Ne jamais le savoir' },
  { left: 'Avoir toujours faim', right: 'Ne jamais avoir faim' },
  { left: 'Ne plus jamais pouvoir mentir', right: 'Ne plus jamais pouvoir recevoir de compliments sincères' },
  { left: 'Gagner à la loterie mais perdre un ami proche', right: 'Ne jamais gagner mais garder tous tes amis' },
  { left: 'Être le/la meilleur·e ami·e de tout le monde', right: 'Avoir un·e seul·e véritable meilleur·e ami·e' },
  { left: 'Vivre sans électricité', right: 'Vivre sans eau courante (mais avec accès à une source proche)' },
  { left: 'Toujours devoir chanter au lieu de parler', right: 'Toujours devoir danser en marchant' },
  { left: 'Ne plus jamais rire', right: 'Ne plus jamais pleurer' },

  // --- Couple / Romance ---
  { left: 'Recevoir des fleurs surprises chaque semaine', right: 'Recevoir un message doux chaque matin' },
  { left: 'Un rendez-vous romantique à la maison, cuisine faite maison', right: 'Un rendez-vous romantique dans un grand restaurant' },
  { left: 'Que ton/ta partenaire te dise « je t’aime » plus souvent', right: 'Qu’il/elle te montre plus de gestes tendres' },
  { left: 'Un week-end romantique à la montagne', right: 'Un week-end romantique à la mer' },
  { left: 'Se tenir la main tout le film', right: 'Un câlin de 10 minutes avant de dormir' },
  { left: 'Connaître toutes les pensées de ton/ta partenaire pendant 1 jour', right: 'Qu’il/elle connaisse toutes les tiennes pendant 1 jour' },
  { left: 'Un slow improvisé dans le salon', right: 'Un pique-nique romantique au coucher de soleil' },
  { left: 'Recevoir une lettre d’amour manuscrite', right: 'Recevoir une chanson composée pour toi' },
  { left: 'Voyager en amoureux sans plan précis', right: 'Voyager en amoureux avec un itinéraire parfaitement organisé' },
  { left: 'Se disputer puis se réconcilier avec un fou rire', right: 'Ne presque jamais se disputer' },
  { left: 'Avoir un·e partenaire très drôle', right: 'Avoir un·e partenaire très romantique' },
  { left: 'Se faire réveiller par un petit-déjeuner au lit', right: 'Se faire réveiller par un massage' },
  { left: 'Danser ensemble devant tout le monde', right: 'Avoir un moment romantique juste tous les deux, en privé' },
  { left: 'Se dire « je t’aime » pour la première fois en public', right: 'Se le dire en privé, juste tous les deux' },
  { left: 'Avoir un surnom mignon en public', right: 'Garder les surnoms uniquement en privé' },
  { left: 'Un date night au cinéma', right: 'Un date night jeux de société' },
  { left: 'Recevoir un cadeau simple mais très symbolique', right: 'Recevoir un cadeau impressionnant mais plus impersonnel' },
  { left: 'Un couple qui communique tout, même les petits détails', right: 'Un couple qui garde un peu de mystère' },
  { left: 'Vieillir ensemble dans une petite maison tranquille', right: 'Vieillir ensemble en voyageant sans arrêt' },
  { left: 'Que ton/ta partenaire te fasse rire tous les jours', right: 'Que ton/ta partenaire te surprenne tous les jours' },
  { left: 'Passer une soirée à cuisiner ensemble', right: 'Passer une soirée à danser ensemble' },
  { left: 'Se rappeler chaque date importante par cœur', right: 'Avoir des rappels mais des surprises plus fréquentes' },
  { left: 'Un rendez-vous surprise organisé par ton/ta partenaire', right: 'Organiser toi-même le rendez-vous parfait' },
  { left: 'Se faire dire des mots doux en public', right: 'Recevoir des petites attentions discrètes' },
  { left: 'Regarder les étoiles ensemble en silence', right: 'Discuter de tout et de rien toute la nuit ensemble' },

  // --- Amis / Soirée ---
  { left: 'Une soirée jeux de société entre amis', right: 'Une soirée dansante entre amis' },
  { left: 'Organiser une soirée surprise pour un ami', right: 'Recevoir une soirée surprise organisée par tes amis' },
  { left: 'Un road trip improvisé avec tes amis', right: 'Des vacances entièrement planifiées avec tes amis' },
  { left: 'Avoir un groupe d’amis restreint mais très soudé', right: 'Avoir un grand cercle d’amis mais moins proche' },
  { left: 'Une soirée pyjama avec films', right: 'Une soirée feu de camp avec histoires' },
  { left: 'Être le/la organisateur/organisatrice du groupe', right: 'Être celui/celle qui suit toujours les plans des autres' },
  { left: 'Un ami qui te dit toujours la vérité, même dure', right: 'Un ami qui te ménage toujours' },
  { left: 'Fêter ton anniversaire en grande soirée', right: 'Fêter ton anniversaire en petit comité intime' },
  { left: 'Voyager entre amis en van aménagé', right: 'Voyager entre amis en tout confort à l’hôtel' },
  { left: 'Un ami hyper drôle mais parfois en retard', right: 'Un ami hyper ponctuel mais plus sérieux' },
  { left: 'Une bataille de jeux vidéo entre amis', right: 'Un tournoi de jeux de société entre amis' },
  { left: 'Refaire le monde autour d’un bon repas', right: 'Refaire le monde en marchant sous les étoiles' },
  { left: 'Que tes amis se souviennent toujours de tes histoires', right: 'Que tes amis se souviennent toujours de tes goûts (musique, plats…)' },
  { left: 'Un ami qui te motive à sortir de ta zone de confort', right: 'Un ami qui respecte toujours ton rythme' },
  { left: 'Un karaoké improvisé entre amis', right: 'Une battle de danse improvisée entre amis' },
  { left: 'Avoir un groupe de discussion très actif', right: 'Avoir peu de messages mais des retrouvailles marquantes' },
  { left: 'Partir en festival de musique entre amis', right: 'Partir en randonnée nature entre amis' },
  { left: 'Un ami qui t’aide à déménager sans se plaindre', right: 'Un ami qui t’écoute pendant des heures sans se lasser' },
  { left: 'Faire une blague à un ami (gentille)', right: 'Recevoir une blague d’un ami (gentille)' },
  { left: 'Que le groupe choisisse toujours le resto', right: 'Que ce soit toujours toi qui choisisses le resto' },

  // --- Famille ---
  { left: 'Un grand repas de famille bruyant et animé', right: 'Un repas calme en petit comité' },
  { left: 'Passer les fêtes chez toi', right: 'Passer les fêtes chez de la famille' },
  { left: 'Avoir beaucoup de cousins et cousines proches', right: 'Être enfant unique dans ta génération' },
  { left: 'Hériter du sens de l’humour d’un parent', right: 'Hériter du talent artistique d’un parent' },
  { left: 'Un road trip en famille', right: 'Des vacances en famille dans un seul endroit tranquille' },
  { left: 'Que ta famille te connaisse par cœur', right: 'Garder un peu de mystère même en famille' },
  { left: 'Reprendre une tradition familiale ancienne', right: 'Créer une toute nouvelle tradition familiale' },
  { left: 'Vivre proche de ta famille toute ta vie', right: 'Vivre loin mais se retrouver pour de grandes occasions' },
  { left: 'Un album photo de famille en version papier', right: 'Un album photo de famille numérique et interactif' },
  { left: 'Passer un dimanche à cuisiner en famille', right: 'Passer un dimanche à jouer à des jeux en famille' },
  { left: 'Ressembler physiquement à ta famille', right: 'Ressembler à ta famille par le caractère' },
  { left: 'Que tes parents racontent tes bêtises d’enfance devant tout le monde', right: 'Que tes parents gardent ça pour eux' },
  { left: 'Avoir des grands-parents très stricts mais justes', right: 'Avoir des grands-parents très permissifs' },
  { left: 'Fêter ton anniversaire en grande fête de famille', right: 'Fêter ton anniversaire en tête-à-tête avec un proche' },
  { left: 'Recevoir des conseils non sollicités de ta famille', right: 'Que ta famille attende toujours que tu demandes' },

  // --- Pouvoirs / Fantastique ---
  { left: 'Avoir la super-force', right: 'Avoir la super-vitesse' },
  { left: 'Pouvoir contrôler le temps qu’il fait', right: 'Pouvoir contrôler les rêves des autres' },
  { left: 'Être un magicien reconnu', right: 'Être un super-héros anonyme' },
  { left: 'Pouvoir respirer sous l’eau', right: 'Pouvoir voler dans les airs' },
  { left: 'Voyager dans le passé', right: 'Voyager dans le futur' },
  { left: 'Avoir un familier magique (dragon, phénix…)', right: 'Avoir des pouvoirs élémentaires (feu, eau, terre, air)' },
  { left: 'Être immortel mais ne jamais pouvoir quitter cette ville', right: 'Vivre normalement mais voyager partout dans le monde' },
  { left: 'Pouvoir te téléporter n’importe où instantanément', right: 'Pouvoir arrêter le temps pendant 1 minute par jour' },
  { left: 'Avoir un pouvoir de guérison', right: 'Avoir un pouvoir de super-intelligence' },
  { left: 'Être invincible mais visible de tous', right: 'Être vulnérable mais pouvoir devenir invisible à volonté' },
  { left: 'Vivre dans un monde de magie', right: 'Vivre dans un monde de technologie ultra avancée' },
  { left: 'Pouvoir parler avec les morts', right: 'Pouvoir lire dans les pensées des vivants' },
  { left: 'Avoir une baguette magique qui exauce 3 vœux', right: 'Avoir un compagnon magique pour la vie' },
  { left: 'Être capable de changer de forme (animal, objet…)', right: 'Être capable de dupliquer temporairement' },
  { left: 'Vivre une aventure épique mais dangereuse', right: 'Vivre une vie tranquille mais sans grande aventure' },

  // --- Dilemmes / Philo léger ---
  { left: 'Savoir toujours si quelqu’un ment', right: 'Ne jamais pouvoir être percé·e à jour' },
  { left: 'Être riche mais peu apprécié·e', right: 'Être modeste mais très aimé·e' },
  { left: 'Vivre 100 vies courtes et différentes', right: 'Vivre 1 seule vie très longue' },
  { left: 'Réussir sans jamais échouer', right: 'Échouer souvent mais apprendre énormément' },
  { left: 'Avoir toutes les réponses mais aucune surprise', right: 'Ne rien savoir d’avance mais garder toute la magie de la surprise' },
  { left: 'Sauver 100 inconnus', right: 'Sauver une seule personne que tu aimes' },
  { left: 'Vivre selon les attentes des autres mais en sécurité', right: 'Vivre selon tes propres choix mais avec plus de risques' },
  { left: 'Avoir un travail que tu adores mais mal payé', right: 'Avoir un travail bien payé mais sans passion' },
  { left: 'Connaître la vérité même si elle fait mal', right: 'Vivre dans une illusion confortable' },
  { left: 'Être respecté·e', right: 'Être aimé·e' },

  // --- Nourriture / Quotidien ---
  { left: 'Ne plus jamais boire de café', right: 'Ne plus jamais boire de thé' },
  { left: 'Manger le même plat pendant 1 mois', right: 'Ne jamais pouvoir remanger ton plat préféré' },
  { left: 'Cuisiner tous les jours', right: 'Faire la vaisselle tous les jours' },
  { left: 'Vivre sans chocolat', right: 'Vivre sans fromage' },
  { left: 'Toujours manger trop épicé', right: 'Toujours manger trop fade' },
  { left: 'Ne manger que du sucré pendant une semaine', right: 'Ne manger que du salé pendant une semaine' },
  { left: 'Avoir un chef cuisinier à domicile', right: 'Avoir une femme/homme de ménage à domicile' },
  { left: 'Petit-déjeuner copieux, dîner léger', right: 'Petit-déjeuner léger, dîner copieux' },
  { left: 'Ne plus jamais commander à emporter', right: 'Ne plus jamais cuisiner toi-même' },
  { left: 'Toujours avoir le dernier mot dans une conversation', right: 'Toujours avoir le dernier morceau du dessert' }
];
