export const ClientEvents = {
  CreateRoom: 'create-room',
  JoinRoom: 'join-room',
  LeaveRoom: 'leave-room',
  ResetMatchScore: 'reset-match-score',
  RpsPlay: 'rps:play',
  OddOrEvenPlay: 'odd-or-even:play',
  TruthOrDareStart: 'truth-or-dare:start',
  TruthOrDareChoice: 'truth-or-dare:choice',
  TruthOrDareAnswer: 'truth-or-dare:answer',
  TruthOrDareValidate: 'truth-or-dare:validate',
  WouldYouRatherStart: 'would-you-rather:start',
  WouldYouRatherChoice: 'would-you-rather:choice',
  TwentyQuestionsSetWord: 'twenty-questions:set-word',
  TwentyQuestionsGuess: 'twenty-questions:guess',
  TwentyQuestionsJudge: 'twenty-questions:judge',
  TwoTruthsOneLieSubmit: 'two-truths-one-lie:submit',
  TwoTruthsOneLieVote: 'two-truths-one-lie:vote',
  RequestGameState: 'game:request-state',
  StartGame: 'start-game'
} as const;

export const ServerEvents = {
  Greeting: 'greeting',
  Hello: 'hello',
  RoomCreated: 'room:created',
  RoomUpdate: 'room:update',
  RoomError: 'room:error',
  ScoreReset: 'score:reset',
  RpsResult: 'rps:result',
  OddOrEvenResult: 'odd-or-even:result',
  TruthOrDareSpin: 'truth-or-dare:spin',
  TruthOrDareContent: 'truth-or-dare:content',
  TruthOrDareAnswerSubmitted: 'truth-or-dare:answer-submitted',
  TruthOrDareResult: 'truth-or-dare:result',
  WouldYouRatherUpdate: 'would-you-rather:update',
  WouldYouRatherResult: 'would-you-rather:result',
  TwentyQuestionsRoundReady: 'twenty-questions:round-ready',
  TwentyQuestionsWordReady: 'twenty-questions:word-ready',
  TwentyQuestionsGuessSubmitted: 'twenty-questions:guess-submitted',
  TwentyQuestionsRoundResult: 'twenty-questions:round-result',
  TwoTruthsOneLiePrompt: 'two-truths-one-lie:prompt',
  TwoTruthsOneLieResult: 'two-truths-one-lie:result',
  TwoTruthsOneLieRoundReady: 'two-truths-one-lie:round-ready',
  GameState: 'game:state',
  GameStarted: 'game:started'
} as const;
